Importing libraries

In [2]:
import tensorflow as tf
import pandas as pd

Preparing the data

In [3]:
filepath = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(filepath)

One hot encoding

In [4]:
iris = pd.get_dummies(iris)

Independent and dependent variables

In [5]:
independent = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent.shape, dependent.shape)

(150, 4) (150, 3)


Design the model

In [6]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

Check the model structure

In [7]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 8)                 72        
                                                                 
 dense_3 (Dense)             (None, 3)                 27        
                                                                 
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


Fit the model with data

In [8]:
model.fit(independent, dependent, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 1.1430 - accuracy: 0.4000
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1066 - accuracy: 0.5867
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0827 - accuracy: 0.6600
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0632 - accuracy: 0.6467
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 1.0450 - accuracy: 0.6600
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0290 - accuracy: 0.6600
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0118 - accuracy: 0.6667
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9963 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 0.9805 - accuracy: 0.6667
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.9660 - accuracy: 0.6667
Epoch 11/100
5/5 [===========

Utilize the model

In [9]:
print(model.predict(independent[:5]))
print(dependent[:5])

[[9.9947864e-01 3.2821400e-04 1.9317887e-04]
 [9.9841630e-01 1.0050951e-03 5.7856110e-04]
 [9.9894112e-01 6.5224670e-04 4.0667626e-04]
 [9.9786699e-01 1.3823820e-03 7.5061171e-04]
 [9.9953020e-01 2.9559707e-04 1.7415464e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
